SELECT 
  FVIL_VESSEL_INV_SK AS FVIL_SHIP_INV_SK
  ,FVIL_DIVISION_SK AS FVIL_REGION_SK
  ,FVIL_SUPPLIER_SK
  ,FVIL_ACCOUNT_SK
  ,FVIL_PROC_ITEM_TYPE_SK
  ,FVIL_INVOICE_DATE_SK
  ,FVIL_INVOICE_LINE_NO
  ,FVIL_VESSEL_PO_SK AS FVIL_SHIP_PO_SK
  ,FVIL_VESSEL_SK AS FVIL_SHIP_SK
  ,FVIL_CURRENCY_SK
  ,FVIL_INVOICE_LINE_CURR_AMT
  ,FVIL_INVOICE_LINE_BASE_AMT
  ,FVIL_INVOICE_LINE_CURR_CAD_AMT
  ,FVIL_INVOICE_LINE_USD_AMT
  ,FVIL_INVOICE_LINE_EUR_AMT
  
FROM dw.FACT_VESSEL_INVOICE_LINES