SELECT 
  FVPOL_VESSEL_PO_SK AS FVPOL_SHIP_PO_SK
  ,FVPOL_VESSEL_PART_SK AS FVPOL_SHIP_PART_SK
  ,FVPOL_VESSEL_SK AS FVPOL_SHIP_SK
  ,FVPOL_DIVISION_SK AS FVPOL_REGION_SK
  ,FVPOL_SUPPLIER_SK
  ,FVPOL_ACCOUNT_SK
  ,FVPOL_PROC_ITEM_TYPE_SK
  ,FVPOL_ORDER_DATE_SK
  ,FVPOL_ORDER_LINE_NO
  ,FVPOL_REQUESTED_DELIVERY_DATE_SK
  ,FVPOL_EXPECTED_DELIVERY_DATE_SK
  ,FVPOL_RECEIVED_DATE_SK
  ,FVPOL_CURRENCY_SK
  ,FVPOL_UNIT_PRICE_AMT
  ,FVPOL_UNIT_PRICE_NET_AMT
  ,FVPOL_UNIT_PRICE_CAD_AMT
  ,FVPOL_UNIT_PRICE_NET_CAD_AMT
  ,FVPOL_REQUESTED_QTY
  ,FVPOL_ORDERED_QTY
  ,FVPOL_RECEIVED_QTY
  ,FVPOL_ORDERED_AMT
  ,FVPOL_ORDERED_NET_AMT
  ,FVPOL_ORDERED_CAD_AMT
  ,FVPOL_ORDERED_NET_CAD_AMT
  
FROM dw.FACT_VESSEL_PO_LINES