SELECT
  dw.FACT_CURRENCY_CONVERSION.FCC_FROM_CURRENCY_SK,
  dw.FACT_CURRENCY_CONVERSION.FCC_TO_CURRENCY_SK,
  dw.FACT_CURRENCY_CONVERSION.FCC_CURRENCY_DATE_SK,
  dw.FACT_CURRENCY_CONVERSION.FCC_CURRENCY_RATE
FROM
  dw.DIM_CURRENCY AS DIM_CURRENCY_TO
  INNER JOIN dw.DIM_CURRENCY AS DIM_CURRENCY_FROM
  INNER JOIN dw.FACT_CURRENCY_CONVERSION ON DIM_CURRENCY_FROM.CURRENCY_SK = dw.FACT_CURRENCY_CONVERSION.FCC_FROM_CURRENCY_SK
  INNER JOIN dw.DIM_TIME ON dw.FACT_CURRENCY_CONVERSION.FCC_CURRENCY_DATE_SK = dw.DIM_TIME.DATE_SK ON DIM_CURRENCY_TO.CURRENCY_SK = dw.FACT_CURRENCY_CONVERSION.FCC_TO_CURRENCY_SK