SELECT
  dw.FACT_MARKET_DATA.FMD_MARKET_DATA_SK,
  dw.FACT_MARKET_DATA.FMD_PUBLICATION_DATE_SK,
  dw.FACT_MARKET_DATA.FMD_VALUE
FROM
  dw.DIM_MARKET_DATA
  INNER JOIN dw.FACT_MARKET_DATA ON dw.DIM_MARKET_DATA.MARKET_DATA_SK = dw.FACT_MARKET_DATA.FMD_MARKET_DATA_SK
  INNER JOIN dw.DIM_TIME ON dw.FACT_MARKET_DATA.FMD_PUBLICATION_DATE_SK = dw.DIM_TIME.DATE_SK