SELECT 
      VENDOR_BANK_SK AS 'SK', 
      VENDOR_BANK_PARTY_ID, 
      VENDOR_BANK_PARTY_SK, 
      VENDOR_BANK_EXT_ACCOUNT_ID AS 'EXT_BANK_ACCOUNT_ID', 
      TRIM(VENDOR_BANK_ACCOUNT_NAME) AS 'BANK_ACCOUNT_NAME', 
      VENDOR_BANK_IBAN, 
      TRIM(VENDOR_BANK_ACCOUNT_NUM) AS 'BANK_ACCOUNT_NUM', 
      VENDOR_BANK_ACCOUNT_CURRENCY_CODE AS 'BANK_ACCOUNT_CURRENCY_CODE', 
      TRIM(VENDOR_BANK_BRANCH_NAME) AS 'BANK_BRANCH_NAME', 
      VENDOR_BANK_EFT_SWIFT_CODE
      -- ETL_CREATED_DATE, 
      -- ETL_CREATED_PROCESS_ID, 
      -- ETL_UPDATED_DATE, 
      -- ETL_UPDATED_PROCESS_ID, 
      -- ETL_HashByte
 FROM dw.DIM_VENDOR_BANK_INFO
