SELECT PILLAR_SK,
      PILLAR_CODE,
      PILLAR_NAME,
      PILLAR_FULL_NAME
      -- ETL_CREATED_DATE,
      -- ETL_CREATED_BY,
      -- ETL_UPDATED_DATE,
      -- ETL_UPDATED_BY,
      -- ETL_PROCESS_ID
FROM dw.DIM_PILLAR
