SELECT
  MARKET_DATA_SK,
  TRIM(MARKET_DATA_CODE) AS MARKET_DATA_CODE,
  TRIM(MARKET_DATA_NAME) AS MARKET_DATA_NAME,
  TRIM(MARKET_DATA_DESC) AS MARKET_DATA_DESC,
  MARKET_DATA_TYPE_SK,
  MARKET_DATA_UOM_SK,
  TRIM(MARKET_DATA_PUBLICATION_FREQUENCY) AS MARKET_DATA_PUBLICATION_FREQUENCY,
  TRIM(MARKET_DATA_ORIGINAL_SOURCE) AS MARKET_DATA_ORIGINAL_SOURCE
--  ETL_CREATED_DATE,
--  ETL_CREATED_PROCESS_ID,
--  ETL_UPDATED_DATE,
--  ETL_UPDATED_PROCESS_ID
FROM
  dw.DIM_MARKET_DATA