SELECT 
	PARTY_SITE_SK, 
	PARTY_SITE_ID, 
	PARTY_SITE_PARTY_SK, 
	TRIM(PARTY_SITE_NAME) AS PARTY_SITE_NAME, 
	PARTY_SITE_STATUS, 
	PARTY_SITE_CREATION_DATE, 
	TRIM(PARTY_SITE_CREATED_BY) AS PARTY_SITE_CREATED_BY, 
	PARTY_SITE_LANGUAGE
	-- ETL_CREATED_DATE, 
	-- ETL_CREATED_BY, 
	-- ETL_UPDATED_DATE, 
	-- ETL_UPDATED_BY, 
	-- ETL_PROCESS_ID
FROM dw.DIM_PARTY_SITES