SELECT
  COUNTRY_SK,
  TRIM(COUNTRY_CODE) AS COUNTRY_CODE,
  TRIM(COUNTRY_NAME) AS COUNTRY_NAME
--  ETL_CREATED_DATE,
--  ETL_CREATED_PROCESS_ID,
--  ETL_UPDATED_DATE,
--  ETL_UPDATED_PROCESS_ID
FROM
  dw.DIM_COUNTRY