SELECT 
	CONV_FROM_CURRENCY_SK, 
	CONV_TO_CURRENCY_SK, 
	CONV_FROM_CURRENCY_CODE, 
	CONV_TO_CURRENCY_CODE, 
	CONV_FROM_CURRENCY_UNIT, 
	CONV_TO_CURRENCY_UNIT, 
	CONV_SECURITY_CODE
	-- ETL_CREATED_DATE, 
	-- ETL_CREATED_PROCESS_ID, 
	-- ETL_UPDATED_DATE, 
	-- ETL_UPDATED_PROCESS_ID
FROM CSLDW.dw.DIM_CURRENCY_CONVERSION_MAPPING_bak
