#!/bin/bash
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.activities
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.boolean
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.decimal
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.enumeration
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.int
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.iterations
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.links
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.long
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.projects
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.releases
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.resources
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.string
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.string_large
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.string_medium
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.timecodes
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.timelines
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.timesheets
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.timestamp
hadoop fs -rm -R /user/hadoop/xpto/rtc/ridw.types
hadoop fs -rm -R /user/hadoop/xpto/rtc/ricalm.requests
