SELECT ---dimensions-------------
	fact.FVPA_VESSEL_PO_SK
      ,fact.FVPA_VESSEL_INV_SK
      ,fact.FVPA_VESSEL_SK
      ,fact.FVPA_REGION_SK
      ,fact.FVPA_SUPPLIER_SK
      ,fact.FVPA_ACCOUNT_SK
      ,fact.FVPA_PROC_ITEM_TYPE_SK
      ,fact.FVPA_CURRENCY_PO_SK
      ,fact.FVPA_CURRENCY_INV_SK
      ,fact.FVPA_ORDER_DATE_SK
      ,fact.FVPA_REQUESTED_DELIVERY_DATE_SK
      ,fact.FVPA_EXPECTED_DELIVERY_DATE_SK
      ,fact.FVPA_RECEIVED_DATE_SK
      ,fact.FVPA_INVOICE_DATE_SK
	  ---measures------------------
      ,FVPA_ORDER_MATERIAL_NET_AMT
      ,FVPA_ORDER_MATERIAL_NET_CAD_AMT
      ,FVPA_ORDER_FREIGHT_AMT
      ,FVPA_ORDER_FREIGHT_CAD_AMT
      ,FVPA_INVOICE_MATERIAL_AMT
      ,FVPA_INVOICE_MATERIAL_CAD_AMT
      ,FVPA_INVOICE_FREIGHT_AMT
      ,FVPA_INVOICE_FREIGHT_CAD_AMT
FROM dw.FACT_VESSEL_PROCUREMENT_AGG fact
JOIN dw.DIM_VESSEL_PO_HEADER po
	ON po.VESSEL_PO_SK = fact.FVPA_VESSEL_PO_SK
JOIN dw.DIM_VESSEL_INVOICE_HEADER inv
	ON inv.VESSEL_INV_SK = fact.FVPA_VESSEL_INV_SK 
JOIN dw.DIM_VESSEL_SHIPSURE ves
	ON ves.VESSEL_SS_SK = fact.FVPA_VESSEL_SK
JOIN dw.DIM_REGION reg
	ON reg.REGION_SK = fact.FVPA_REGION_SK
JOIN dw.DIM_CONTACT_SHIPSURE supp
	ON supp.CONTACT_SS_SK = fact.FVPA_SUPPLIER_SK
JOIN dw.DIM_ACCOUNT_SHIPSURE acc
	ON acc.ACCOUNT_SS_SK = fact.FVPA_ACCOUNT_SK
JOIN dw.DIM_PROCUREMENT_ITEM_TYPE itemtype
	ON itemtype.PROC_ITEM_TYPE_SK = fact.FVPA_PROC_ITEM_TYPE_SK
JOIN dw.DIM_CURRENCY currpo
	ON currpo.CURRENCY_SK = fact.FVPA_CURRENCY_PO_SK
JOIN dw.DIM_CURRENCY currinv
	ON currinv.CURRENCY_SK = fact.FVPA_CURRENCY_INV_SK