SELECT
  fact.FVEL_VESSEL_PO_SK,
  fact.FVEL_VESSEL_PART_SK,
  fact.FVEL_VESSEL_COMP_SK,
  fact.FVEL_VESSEL_SK,
  fact.FVEL_REGION_SK,
  fact.FVEL_SUPPLIER_SK,
  fact.FVEL_ACCOUNT_PROC_SK,
  fact.FVEL_PROC_ITEM_TYPE_SK,
  fact.FVEL_ENQR_LINE_NO,
  fact.FVEL_ENQR_STATUS_SK,
  fact.FVEL_ENQR_STATUS_DATE,
  fact.FVEL_CURRENCY_SK,
  fact.FVEL_REQS_CREATED_DATE_SK,
  fact.FVEL_REQS_ENTRD_DATE_SK,
  fact.FVEL_REQUESTED_DELIVERY_DATE_SK,
  fact.FVEL_EXPECTED_DELIVERY_DATE_SK,
  fact.FVEL_UNIT_PRICE_AMT,
  fact.FVEL_UNIT_PRICE_CAD_AMT,
  fact.FVEL_ENQUIRY_QTY,
  fact.FVEL_ENQUIRY_AMT,
  fact.FVEL_ENQUIRY_CAD_AMT,
  fact.FVEL_ENQUIRY_SUPPLIER_AMT,
  fact.FVEL_ENQUIRY_SUPPLIER_CAD_AMT
FROM
  dw.FACT_VESSEL_ENQUIRY_LINES AS fact
  INNER JOIN dw.DIM_VESSEL_PO_HEADER AS po ON po.VESSEL_PO_SK = fact.FVEL_VESSEL_PO_SK
  INNER JOIN dw.DIM_VESSEL_PART AS part ON part.VESSEL_PART_SK = fact.FVEL_VESSEL_PART_SK
  INNER JOIN dw.DIM_VESSEL_COMPONENT AS com ON com.VESSEL_COMP_SK = fact.FVEL_VESSEL_COMP_SK
  INNER JOIN dw.DIM_VESSEL_SHIPSURE AS ves ON ves.VESSEL_SS_SK = fact.FVEL_VESSEL_SK
  INNER JOIN dw.DIM_REGION AS reg ON reg.REGION_SK = fact.FVEL_REGION_SK
  INNER JOIN dw.DIM_CONTACT_SHIPSURE AS supp ON supp.CONTACT_SS_SK = fact.FVEL_SUPPLIER_SK
  INNER JOIN dw.DIM_ACCOUNT_SHIPSURE AS acc ON acc.ACCOUNT_SS_SK = fact.FVEL_ACCOUNT_PROC_SK
  INNER JOIN dw.DIM_PROCUREMENT_ITEM_TYPE AS itemtype ON itemtype.PROC_ITEM_TYPE_SK = fact.FVEL_PROC_ITEM_TYPE_SK
  INNER JOIN dw.DIM_PROCUREMENT_STATUS AS sta ON sta.PROC_STATUS_SK = fact.FVEL_ENQR_STATUS_SK
  INNER JOIN dw.DIM_CURRENCY AS curr ON curr.CURRENCY_SK = fact.FVEL_CURRENCY_SK