SELECT
  fact.FVWODAS_SNAPSHOT_DATE_SK,
  fact.FVWODAS_VESSEL_SS_SK,
  fact.FVWODAS_DEPT_SS_SK,
  fact.FVWODAS_JOB_CLASS_SS_SK,
  fact.FVWODAS_DIVISION_SK,
  fact.FVWODAS_WO_TYPE_SK,
  fact.FVWODAS_NB_JOB_DUE_CRITICAL,
  fact.FVWODAS_NB_JOB_DUE_CSM,
  fact.FVWODAS_NB_JOB_DUE_OTHER,
  fact.FVWODAS_NB_JOB_OVERDUE_CRITICAL,
  fact.FVWODAS_NB_JOB_OVERDUE_CSM,
  fact.FVWODAS_NB_JOB_OVERDUE_OTHER,
  fact.FVWODAS_NB_JOB_RESCHEDULED
FROM
  dw.FACT_VESSEL_WORK_ORDER_DUE_AGG_SNAPSHOT AS fact
  INNER JOIN dw.DIM_VESSEL_SHIPSURE AS ves ON ves.VESSEL_SS_SK = fact.FVWODAS_VESSEL_SS_SK
  INNER JOIN dw.DIM_DEPARTMENT_SHIPSURE AS dept ON dept.DEPT_SS_SK = fact.FVWODAS_DEPT_SS_SK
  INNER JOIN dw.DIM_JOB_CLASS_SHIPSURE AS jobclass ON jobclass.JOB_CLASS_SS_SK = fact.FVWODAS_JOB_CLASS_SS_SK
  INNER JOIN dw.DIM_REGION AS reg ON reg.REGION_SK = fact.FVWODAS_DIVISION_SK
  INNER JOIN dw.DIM_WORK_ORDER_TYPE AS wo ON wo.WO_TYPE_SK = fact.FVWODAS_WO_TYPE_SK