SELECT ---dimensions-------------
	 fact.FVPCS_VESSEL_PO_SK
      ,fact.FVPCS_VESSEL_SK
      ,fact.FVPCS_REGION_SK
      ,fact.FVPCS_ACCOUNT_PROC_SK
      ,fact.FVPCS_PROC_ITEM_TYPE_SK
      ,fact.FVPCS_REQUESTED_DELVR_DATE
      ,fact.FVPCS_EXPECTED_DELVR_DATE
      ,fact.FVPCS_RECEIVED_DELVR_DATE
      ,fact.FVPCS_REQS_FIRST_STATUS_SK
      ,fact.FVPCS_REQS_FIRST_STATUS_DATE
      ,fact.FVPCS_ENQR_FIRST_STATUS_SK
      ,fact.FVPCS_ENQR_FIRST_STATUS_DATE
      ,fact.FVPCS_ENQR_EO_STATUS_DATE
      ,fact.FVPCS_ENQR_EP_STATUS_DATE
      ,fact.FVPCS_ENQR_TA_STATUS_DATE
      ,fact.FVPCS_ENQR_TR_STATUS_DATE
      ,fact.FVPCS_AUTH_ENQR_FIRST_STATUS_SK
      ,fact.FVPCS_AUTH_ENQR_FIRST_STATUS_DATE
	  ---measures------------------
      ,FVPCS_REQS_PL_TO_RE_DAYS_NUM
      ,FVPCS_REQS_TO_ENQR_DAYS_NUM
      ,FVPCS_PO_DELVR_DAYS_NUM
      ,FVPCS_PO_RECV_DAYS_NUM
      ,FVPCS_ENQR_EO_TO_EP_DAYS_NUM
      ,FVPCS_ENQR_EP_TO_TA_DAYS_NUM
      ,FVPCS_ENQR_TA_TO_TR_DAYS_NUM
      ,FVPCS_ENQR_TO_AUTH_ENQR_DAYS_NUM
      ,FVPCS_PO_DW_TO_SW_DAYS_NUM
      ,FVPCS_PO_DW_TO_RV_DAYS_NUM
      ,FVPCS_PO_DW_TO_RT_DAYS_NUM
      ,FVPCS_PO_DW_TO_PD_DAYS_NUM
      ,FVPCS_PO_O_TO_SW_DAYS_NUM
      ,FVPCS_PO_O_TO_RV_DAYS_NUM
      ,FVPCS_PO_O_TO_RT_DAYS_NUM
      ,FVPCS_PO_O_TO_PD_DAYS_NUM
      ,FVPCS_PO_SW_TO_RV_DAYS_NUM
      ,FVPCS_PO_SW_TO_RT_DAYS_NUM
      ,FVPCS_PO_SW_TO_PD_DAYS_NUM
FROM dw.FACT_VESSEL_PROCUREMENT_CUMUL_SNAPSHOT fact
JOIN dw.DIM_VESSEL_PO_HEADER po
	ON po.VESSEL_PO_SK = fact.FVPCS_VESSEL_PO_SK 
JOIN dw.DIM_VESSEL_SHIPSURE ves
	ON ves.VESSEL_SS_SK = fact.FVPCS_VESSEL_SK
JOIN dw.DIM_REGION reg
	ON reg.REGION_SK = fact.FVPCS_REGION_SK
JOIN dw.DIM_ACCOUNT_SHIPSURE acc
	ON acc.ACCOUNT_SS_SK = fact.FVPCS_ACCOUNT_PROC_SK
JOIN dw.DIM_PROCUREMENT_ITEM_TYPE itemtype
	ON itemtype.PROC_ITEM_TYPE_SK = fact.FVPCS_PROC_ITEM_TYPE_SK
LEFT JOIN dw.DIM_PROCUREMENT_STATUS stareq
	ON stareq.PROC_STATUS_SK = fact.FVPCS_REQS_FIRST_STATUS_SK
LEFT JOIN dw.DIM_PROCUREMENT_STATUS staenq
	ON staenq.PROC_STATUS_SK = fact.FVPCS_ENQR_FIRST_STATUS_SK
LEFT JOIN dw.DIM_PROCUREMENT_STATUS staauthenqr
	ON staauthenqr.PROC_STATUS_SK = fact.FVPCS_AUTH_ENQR_FIRST_STATUS_SK
LEFT JOIN dw.DIM_PROCUREMENT_STATUS stapo
	ON stapo.PROC_STATUS_SK = fact.FVPCS_PO_FIRST_STATUS_SK