SELECT
  fact.FVESCS_VESSEL_PO_SK,
  fact.FVESCS_VESSEL_SK,
  fact.FVESCS_REGION_SK,
  fact.FVESCS_SUPPLIER_SK,
  fact.FVESCS_ACCOUNT_PROC_SK,
  fact.FVESCS_PROC_ITEM_TYPE_SK,
  fact.FVESCS_SUPPL_LAST_STATUS_SK,
  fact.FVESCS_SUPPL_EP_STATUS_DATE,
  fact.FVESCS_SUPPL_TI_STATUS_DATE,
  fact.FVESCS_SUPPL_TH_STATUS_DATE,
  fact.FVESCS_SUPPL_TX_STATUS_DATE,
  fact.FVESCS_SUPPL_TA_STATUS_DATE,
  fact.FVESCS_SUPPL_EP_TO_TA_DAYS_NUM
FROM
  dw.FACT_VESSEL_ENQR_SUPPL_CUMUL_SNAPSHOT AS fact
  INNER JOIN dw.DIM_VESSEL_PO_HEADER AS po ON po.VESSEL_PO_SK = fact.FVESCS_VESSEL_PO_SK
  INNER JOIN dw.DIM_VESSEL_SHIPSURE AS ves ON ves.VESSEL_SS_SK = fact.FVESCS_VESSEL_SK
  INNER JOIN dw.DIM_REGION AS reg ON reg.REGION_SK = fact.FVESCS_REGION_SK
  INNER JOIN dw.DIM_CONTACT_SHIPSURE AS supp ON supp.CONTACT_SS_SK = fact.FVESCS_SUPPLIER_SK
  INNER JOIN dw.DIM_ACCOUNT_SHIPSURE AS acc ON acc.ACCOUNT_SS_SK = fact.FVESCS_ACCOUNT_PROC_SK
  INNER JOIN dw.DIM_PROCUREMENT_ITEM_TYPE AS itemtype ON itemtype.PROC_ITEM_TYPE_SK = fact.FVESCS_PROC_ITEM_TYPE_SK
  LEFT OUTER JOIN dw.DIM_PROCUREMENT_STATUS AS sta ON sta.PROC_STATUS_SK = fact.FVESCS_SUPPL_LAST_STATUS_SK