SELECT ---dimensions-------------
	fact.FVPOL_VESSEL_PO_SK
      ,fact.FVPOL_VESSEL_PART_SK
      ,fact.FVPOL_VESSEL_SK
      ,fact.FVPOL_DIVISION_SK
      ,fact.FVPOL_SUPPLIER_SK
      ,fact.FVPOL_ACCOUNT_SK
      ,fact.FVPOL_PROC_ITEM_TYPE_SK
      ,fact.FVPOL_ORDER_DATE_SK
      ,fact.FVPOL_ORDER_LINE_NO
      ,fact.FVPOL_REQUESTED_DELIVERY_DATE_SK
      ,fact.FVPOL_EXPECTED_DELIVERY_DATE_SK
      ,fact.FVPOL_RECEIVED_DATE_SK
      ,fact.FVPOL_CURRENCY_SK
	  ---measures------------------
      ,FVPOL_UNIT_PRICE_AMT
      ,FVPOL_UNIT_PRICE_NET_AMT
      ,FVPOL_UNIT_PRICE_CAD_AMT
      ,FVPOL_UNIT_PRICE_NET_CAD_AMT
      ,FVPOL_REQUESTED_QTY
      ,FVPOL_ORDERED_QTY
      ,FVPOL_RECEIVED_QTY
      ,FVPOL_ORDERED_AMT
      ,FVPOL_ORDERED_NET_AMT
      ,FVPOL_ORDERED_CAD_AMT
      ,FVPOL_ORDERED_NET_CAD_AMT
FROM dw.FACT_VESSEL_PO_LINES fact
JOIN dw.DIM_VESSEL_PO_HEADER po
	ON po.VESSEL_PO_SK = fact.FVPOL_VESSEL_PO_SK
JOIN dw.DIM_VESSEL_PART part
	ON part.VESSEL_PART_SK = fact.FVPOL_VESSEL_PART_SK
JOIN dw.DIM_VESSEL_SHIPSURE ves
	ON ves.VESSEL_SS_SK = fact.FVPOL_VESSEL_SK
JOIN dw.DIM_REGION reg 
	ON reg.REGION_SK = fact.FVPOL_DIVISION_SK
JOIN dw.DIM_CONTACT_SHIPSURE supp
	ON supp.CONTACT_SS_SK = fact.FVPOL_SUPPLIER_SK
JOIN dw.DIM_ACCOUNT_SHIPSURE acc
	ON acc.ACCOUNT_SS_SK = fact.FVPOL_ACCOUNT_SK
JOIN dw.DIM_PROCUREMENT_ITEM_TYPE itemtype
	ON itemtype.PROC_ITEM_TYPE_SK = fact.FVPOL_PROC_ITEM_TYPE_SK
JOIN dw.DIM_CURRENCY curr
	ON curr.CURRENCY_SK = fact.FVPOL_CURRENCY_SK
WHERE fact.FVPOL_ORDER_DATE_SK 
	BETWEEN CAST(CONVERT(char(8), getdate()-91,112) as int) -- filter on a primary key to reduce query execution time (last 90 days since yesterday)
	AND CAST(CONVERT(char(8), getdate()-1,112) as int)