SELECT
  fact.FVRL_VESSEL_PO_SK,
  fact.FVRL_VESSEL_PART_SK,
  fact.FVRL_VESSEL_COMP_SK,
  fact.FVRL_VESSEL_SK,
  fact.FVRL_REGION_SK,
  fact.FVRL_SUPPLIER_SK,
  fact.FVRL_ACCOUNT_PROC_SK,
  fact.FVRL_PROC_ITEM_TYPE_SK,
  fact.FVRL_REQS_LINE_NO,
  fact.FVRL_REQS_STATUS_SK,
  fact.FVRL_REQS_STATUS_DATE,
  fact.FVRL_CURRENCY_SK,
  fact.FVRL_REQS_CREATED_DATE_SK,
  fact.FVRL_REQS_ENTRD_DATE_SK,
  fact.FVRL_REQUESTED_DELIVERY_DATE_SK,
  fact.FVRL_EXPECTED_DELIVERY_DATE_SK,
  fact.FVRL_REQUESTED_QTY
FROM
  dw.FACT_VESSEL_REQUISITION_LINES AS fact
  INNER JOIN dw.DIM_VESSEL_PO_HEADER AS po ON po.VESSEL_PO_SK = fact.FVRL_VESSEL_PO_SK
  INNER JOIN dw.DIM_VESSEL_PART AS part ON part.VESSEL_PART_SK = fact.FVRL_VESSEL_PART_SK
  INNER JOIN dw.DIM_VESSEL_COMPONENT AS com ON com.VESSEL_COMP_SK = fact.FVRL_VESSEL_COMP_SK
  INNER JOIN dw.DIM_VESSEL_SHIPSURE AS ves ON ves.VESSEL_SS_SK = fact.FVRL_VESSEL_SK
  INNER JOIN dw.DIM_REGION AS reg ON reg.REGION_SK = fact.FVRL_REGION_SK
  INNER JOIN dw.DIM_CONTACT_SHIPSURE AS supp ON supp.CONTACT_SS_SK = fact.FVRL_SUPPLIER_SK
  INNER JOIN dw.DIM_ACCOUNT_SHIPSURE AS acc ON acc.ACCOUNT_SS_SK = fact.FVRL_ACCOUNT_PROC_SK
  INNER JOIN dw.DIM_PROCUREMENT_ITEM_TYPE AS itemtype ON itemtype.PROC_ITEM_TYPE_SK = fact.FVRL_PROC_ITEM_TYPE_SK
  INNER JOIN dw.DIM_PROCUREMENT_STATUS AS sta ON sta.PROC_STATUS_SK = fact.FVRL_REQS_STATUS_SK
  INNER JOIN dw.DIM_CURRENCY AS curr ON curr.CURRENCY_SK = fact.FVRL_CURRENCY_SK
