SELECT
  dw.FACT_CURRENCY_CONVERSION.FCC_FROM_CURRENCY_SK,
  dw.FACT_CURRENCY_CONVERSION.FCC_TO_CURRENCY_SK,
  dw.FACT_CURRENCY_CONVERSION.FCC_CURRENCY_DATE_SK,
  dw.FACT_CURRENCY_CONVERSION.FCC_CURRENCY_RATE
--  dw.FACT_CURRENCY_CONVERSION.ETL_CREATED_DATE,
--  dw.FACT_CURRENCY_CONVERSION.ETL_CREATED_PROCESS_ID,
--  dw.FACT_CURRENCY_CONVERSION.ETL_UPDATED_DATE,
--  dw.FACT_CURRENCY_CONVERSION.ETL_UPDATED_PROCESS_ID
FROM
  dw.FACT_CURRENCY_CONVERSION
  INNER JOIN dw.DIM_CURRENCY AS DIM_CURRENCY_TO ON dw.FACT_CURRENCY_CONVERSION.FCC_TO_CURRENCY_SK = DIM_CURRENCY_TO.CURRENCY_SK
  INNER JOIN dw.DIM_CURRENCY AS DIM_CURRENCY_FROM ON dw.FACT_CURRENCY_CONVERSION.FCC_FROM_CURRENCY_SK = DIM_CURRENCY_FROM.CURRENCY_SK
  INNER JOIN dw.DIM_TIME ON dw.FACT_CURRENCY_CONVERSION.FCC_CURRENCY_DATE_SK = dw.DIM_TIME.DATE_SK