SELECT 
    VESSEL_SS_SK
    ,VESSEL_SS_CODE
    ,VESSEL_SS_NAME
    ,VESSEL_SS_ACTIVE_FLAG
    ,ETL_CREATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_DATE
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_VESSEL_SHIPSURE