SELECT 
    DEPT_SS_SK
    ,DEPT_SS_CODE
    ,DEPT_SS_RESPONSIBLE
    ,DEPT_SS_GROUP_NAME
    ,ETL_CREATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_DATE
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_DEPARTMENT_SHIPSURE