SELECT 
    PROC_STATUS_SK
    ,PROC_STAGE_NAME
    ,PROC_STATUS_CODE
    ,PROC_STATUS_NAME
    ,ETL_CREATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_DATE
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_PROCUREMENT_STATUS