SELECT 
    VESSEL_PART_SK
    ,VESSEL_PART_CODE
    ,VESSEL_PART_NAME
    ,VESSEL_PART_UOM
    ,VESSEL_PART_UOM_DESC
    ,VESSEL_PART_MAKERS_REF_DESC
    ,VESSEL_PART_DRAWING_POS_DESC
    ,ETL_CREATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_DATE
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_VESSEL_PART