SELECT 
    PROC_ITEM_TYPE_SK
    ,PROC_ITEM_TYPE_CODE
    ,PROC_ITEM_TYPE_NAME
    ,ETL_CREATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_DATE
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_PROCUREMENT_ITEM_TYPE