SELECT 
    ACCOUNT_SS_SK
    ,ACCOUNT_SS_CODE
    ,ACCOUNT_SS_NAME
    ,ACCOUNT_SS_CURR_ORIG_CODE
    ,ACCOUNT_SS_CURR_CODE
    ,ACCOUNT_SS_CURR_SK
    ,ETL_CREATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_DATE
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_ACCOUNT_SHIPSURE