SELECT 
    JOB_CLASS_SS_SK
    ,JOB_CLASS_SS_CODE
    ,JOB_CLASS_SS_DESC
    ,ETL_CREATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_DATE
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_JOB_CLASS_SHIPSURE