SELECT 
    REF_CODE_SK
    ,REF_SUBJECT_NAME
    ,REF_CODE_NAME
    ,REF_CODE_VALUE
    ,REF_CODE_VALUE_DESC_EN
    ,REF_CODE_VALUE_DESC_FR
    ,ETL_CREATED_DATE
    ,ETL_UPDATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_REFERENCE_CODE