SELECT 
    MAINT_JOB_SK
    ,MAINT_JOB_CODE
    ,MAINT_JOB_NAME
    ,MAINT_JOB_CLASS_SS_SK
    ,MAINT_JOB_DEPT_SS_SK
    ,MAINT_JOB_CANCEL_FLAG
    ,MAINT_JOB_CANCEL_DATE
    ,ETL_CREATED_DATE
    ,ETL_CREATED_PROCESS_ID
    ,ETL_UPDATED_DATE
    ,ETL_UPDATED_PROCESS_ID
FROM dw.DIM_MAINTENANCE_JOB