SELECT
  DEPT_SS_SK,
  TRIM(DEPT_SS_CODE) AS DEPT_SS_CODE,
  TRIM(DEPT_SS_RESPONSIBLE) AS DEPT_SS_RESPONSIBLE,
  TRIM(DEPT_SS_GROUP_NAME) AS DEPT_SS_GROUP_NAME
--  ETL_CREATED_DATE,
--  ETL_CREATED_PROCESS_ID,
--  ETL_UPDATED_DATE,
--  ETL_UPDATED_PROCESS_ID
FROM
  dw.DIM_DEPARTMENT_SHIPSURE