SELECT 
  RESCH_REASON_SK,
  RESCH_REASON_CODE,
  RESCH_DATE,
  RESCH_REASON_TYPE,
  TRIM(RESCH_REASON_COMMENT) AS RESCH_REASON_COMMENT,
  RESCH_BY_NAME,
  RESCH_ON_DATE
  -- ETL_CREATED_DATE
  -- ETL_CREATED_PROCESS_ID
  -- ETL_UPDATED_DATE
  -- ETL_UPDATED_PROCESS_ID
  FROM dw.DIM_RESCHEDULED_REASON
