SELECT
  VESSEL_PART_SK,
  TRIM(VESSEL_PART_CODE) AS VESSEL_PART_CODE,
  TRIM(VESSEL_PART_NAME) AS VESSEL_PART_NAME,
  TRIM(VESSEL_PART_UOM) AS VESSEL_PART_UOM,
  TRIM(VESSEL_PART_UOM_DESC) AS VESSEL_PART_UOM_DESC,
  TRIM(VESSEL_PART_MAKERS_REF_DESC) AS VESSEL_PART_MAKERS_REF_DESC,
  TRIM(VESSEL_PART_DRAWING_POS_DESC) AS VESSEL_PART_DRAWING_POS_DESC,
--  ETL_CREATED_DATE,
--  ETL_CREATED_PROCESS_ID,
--  ETL_UPDATED_DATE,
--  ETL_UPDATED_PROCESS_ID
FROM
  dw.DIM_VESSEL_PART