SELECT
  PROC_ITEM_TYPE_SK,
  TRIM(PROC_ITEM_TYPE_CODE) AS PROC_ITEM_TYPE_CODE,
  TRIM(PROC_ITEM_TYPE_NAME) AS PROC_ITEM_TYPE_NAME
--  ETL_CREATED_DATE,
--  ETL_CREATED_PROCESS_ID,
--  ETL_UPDATED_DATE,
--  ETL_UPDATED_PROCESS_ID
FROM
  dw.DIM_PROCUREMENT_ITEM_TYPE