SELECT
  CONTACT_SS_SK,
  TRIM(CONTACT_SS_CODE) AS CONTACT_SS_CODE,
  TRIM(CONTACT_SS_NAME) AS CONTACT_SS_NAME,
  TRIM(CONTACT_SS_COUNTRY_CODE) AS CONTACT_SS_COUNTRY_CODE,
  TRIM(CONTACT_SS_COUNTRY_NAME) AS CONTACT_SS_COUNTRY_NAME,
  TRIM(CONTACT_SS_CITY_NAME) AS CONTACT_SS_CITY_NAME,
  TRIM(CONTACT_SS_ADDR) AS CONTACT_SS_ADDR,
  TRIM(CONTACT_SS_STATE_NAME) AS CONTACT_SS_STATE_NAME,
  TRIM(CONTACT_SS_POST_CODE) AS CONTACT_SS_POST_CODE,
  TRIM(CONTACT_SS_PHONE_NO) AS CONTACT_SS_PHONE_NO,
  TRIM(CONTACT_SS_MOBILE_NO) AS CONTACT_SS_MOBILE_NO,
  TRIM(CONTACT_SS_EMAIL_ADR) AS CONTACT_SS_EMAIL_ADR,
  TRIM(CONTACT_SS_OTHER_EMAIL_ADR) AS CONTACT_SS_OTHER_EMAIL_ADR
--  ETL_CREATED_DATE,
--  ETL_CREATED_PROCESS_ID,
--  ETL_UPDATED_DATE,
--  ETL_UPDATED_PROCESS_ID
FROM
  dw.DIM_CONTACT_SHIPSURE