SELECT
  VESSEL_COMP_SK,
  TRIM(VESSEL_COMP_CODE) AS VESSEL_COMP_CODE,
  TRIM(VESSEL_COMP_NAME) AS VESSEL_COMP_NAME,
  TRIM(VESSEL_COMP_TYPE_ORIG_CODE) AS VESSEL_COMP_TYPE_ORIG_CODE,
  TRIM(VESSEL_COMP_TYPE_DESC) AS VESSEL_COMP_TYPE_DESC,
  TRIM(VESSEL_COMP_CLASS_CODE) AS VESSEL_COMP_CLASS_CODE,
  TRIM(VESSEL_COMP_MODEL_DESC) AS VESSEL_COMP_MODEL_DESC,
  TRIM(VESSEL_COMP_SERIAL_NO) AS VESSEL_COMP_SERIAL_NO,
  TRIM(VESSEL_COMP_POSITION_SHORT_DESC) AS VESSEL_COMP_POSITION_SHORT_DESC,
  VESSEL_COMP_CRITICAL_FLAG,
  VESSEL_COMP_DELETE_OR_INACTIVE_FLAG,
  VESSEL_COMP_DELETE_OR_INACTIVE_DATE,
  TRIM(VESSEL_COMP_VESSEL_ORIG_CODE) AS VESSEL_COMP_SHIP_ORIG_CODE,
  VESSEL_COMP_VESSEL_SK AS VESSEL_COMP_SHIP_SK
--  ETL_CREATED_DATE,
--  ETL_CREATED_PROCESS_ID,
--  ETL_UPDATED_DATE,
--  ETL_UPDATED_PROCESS_ID
FROM
  dw.DIM_VESSEL_COMPONENT
