SELECT PROC_STATUS_SK,
 PROC_STAGE_NAME as stage_name,
 PROC_STATUS_CODE as status_code,
 PROC_STATUS_NAME as status_name
-- ETL_CREATED_DATE,
-- ETL_CREATED_PROCESS_ID,
-- ETL_UPDATED_DATE,
-- ETL_UPDATED_PROCESS_ID
FROM dw.DIM_PROCUREMENT_STATUS